name: flutter_form_validator_example

publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_form_validator:
    path: ../

flutter:
  uses-material-design: true